base:
  project_name: News Article Sorting
  target: Category
  random_state: 8
plot:
  eda_count_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\eda_plot_with_count.png
  eda_freq_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\eda_plot_with_frequency.png
  testdata_eda_count_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\testdata_eda_plot_with_count.png
  testdata_eda_freq_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\testdata_eda_plot_with_frequency.png

data_source:
  sample_submission: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Sample solution.csv
  train: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Train.csv
  test: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Test.csv

load_data:
  X_train: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\X_train.pickle
  X_test: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\X_train.pickle
  y_train: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\y_train.pickle
  y_test: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\y_test.pickle
  X_train_before_tfidf: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\X_train_before_tfidf.pickle
  X_test_before_tfidf: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\X_test_before_tfidf.pickle
  tfidf: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\tfidf.pickle

tfidf:
  ngram_range: (1, 2)
  max_df: 1.0
  min_df: 10
  max_features: 300
  lowercase: False

knn:
  randomize_search:
    cv: 5
    verbose: 1
    scoring: accuracy,
    n_iter: 30,
    
  grid_search:
    scoring: accuracy
    verbose: 1
  
  save_dataframe: newsarticlesorting\model_accuracy\knn_dataframe.pickle
  save_model: newsarticlesorting\model\knn_model.pickle

